### ISSUE TITLE
About Training processing 

### ISSUE THREAD

**Issue by Louis-Leee** [megvii-research/OccDepth#3]
Dear Authors:

I write the issue to ask for help in the training process of OccDepth:

1) If it is convenient, can you release your model file based on multicam_flospdepth_crp_stereodepth_cascadecls_2080ti.yaml？

2)When I tried to train the model, I found that the process is really slow on my workstation:
/home/duan/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
Epoch 0:   3%|███▍                                                                                                      | 38/1163 [06:42<3:13:32, 10.32s/it, loss=17.4, v_num=]

It seems cost 3.5h for one epoch on 4 A6000 48G GPUs, I just want to know, how much time will you spend to train a model with 30 epochs you mentioned in the .yaml? and are there any wrong settings or something needs to do?

**Comment by rhmiao** [comment]
@Louis-Leee 
You can download models from [Readme#trained-models](https://github.com/megvii-research/OccDepth#trained-models).

It takes about 1h30min/epoch when training our models on GeForce RTX 2080 Ti x 8 with 200g memory and 20 cpus. Maybe you need to check number of cpus and memory.

**Comment by Louis-Leee** [comment]
Thanks for your reply!

**Comment by Jessy-Huang** [comment]
请问您的mmcv是怎么安装上去的，我的mmcv 1.4.0怎么都安装不上去

**Comment by Louis-Leee** [comment]
mmcv与pytorch等库有对应版本，可以查看mmcv的官方文档进行选择
mmcv 1.4.0的可以运行，最新的cuda11.7对应的mmcv经测试也可以运行occdepth
或许你可以按照https://github.com/NVlabs/VoxFormer/blob/main/docs/install.md 试一试

**Comment by Jessy-Huang** [comment]
安装mmcv现在不报错了，但是运行generate_output报错
python occdepth/scripts/generate_output.py n_gpus=4 batch_size_per_gpu=1
/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py:28: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmdet/models/utils/transformer.py:27: UserWarning: `MultiScaleDeformableAttention` in MMCV has been moved to `mmcv.ops.multi_scale_deform_attn`, please update your MMCV
  '`MultiScaleDeformableAttention` in MMCV has been moved to '
Traceback (most recent call last):
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmdet/models/utils/transformer.py", line 23, in <module>
    from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmcv/ops/assign_score_withk.py", line 6, in <module>
    '_ext', ['assign_score_withk_forward', 'assign_score_withk_backward'])
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "occdepth/scripts/generate_output.py", line 2, in <module>
    from occdepth.models.OccDepth import OccDepth
  File "/media/hjc/DeepLearning1/DLProjects/Robot-binocular-vision/OccDepth-main/occdepth/models/OccDepth.py", line 18, in <module>
    from occdepth.models.flosp_depth.flosp_depth import FlospDepth
  File "/media/hjc/DeepLearning1/DLProjects/Robot-binocular-vision/OccDepth-main/occdepth/models/flosp_depth/flosp_depth.py", line 4, in <module>
    from mmdet.models.backbones.resnet import BasicBlock
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmdet/models/backbones/csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmdet/models/utils/__init__.py", line 16, in <module>
    from .transformer import (DetrTransformerDecoder, DetrTransformerDecoderLayer,
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmdet/models/utils/transformer.py", line 29, in <module>
    from mmcv.cnn.bricks.transformer import MultiScaleDeformableAttention
ImportError: cannot import name 'MultiScaleDeformableAttention' from 'mmcv.cnn.bricks.transformer' (/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py)

从 Windows 版邮件发送

发件人: Sihang Li
发送时间: 2023年4月3日 14:35
收件人: megvii-research/OccDepth
抄送: Jessy-Huang; Comment
主题: Re: [megvii-research/OccDepth] About Training processing (Issue #3)

mmcv与pytorch等库有对应版本，可以查看mmcv的官方文档进行选择
mmcv 1.4.0的可以运行，最新的cuda11.7对应的mmcv经测试也可以运行occdepth
或许你可以按照https://github.com/NVlabs/VoxFormer/blob/main/docs/install.md 试一试

**Comment by Jessy-Huang** [comment]
安装mmcv没有报错了，但是运行仍然有下面的报错generate_output

python occdepth/scripts/generate_output.py n_gpus=4 batch_size_per_gpu=1
/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py:28: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmdet/models/utils/transformer.py:27: UserWarning: `MultiScaleDeformableAttention` in MMCV has been moved to `mmcv.ops.multi_scale_deform_attn`, please update your MMCV
  '`MultiScaleDeformableAttention` in MMCV has been moved to '
Traceback (most recent call last):
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmdet/models/utils/transformer.py", line 23, in <module>
    from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmcv/ops/assign_score_withk.py", line 6, in <module>
    '_ext', ['assign_score_withk_forward', 'assign_score_withk_backward'])
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "occdepth/scripts/generate_output.py", line 2, in <module>
    from occdepth.models.OccDepth import OccDepth
  File "/media/hjc/DeepLearning1/DLProjects/Robot-binocular-vision/OccDepth-main/occdepth/models/OccDepth.py", line 18, in <module>
    from occdepth.models.flosp_depth.flosp_depth import FlospDepth
  File "/media/hjc/DeepLearning1/DLProjects/Robot-binocular-vision/OccDepth-main/occdepth/models/flosp_depth/flosp_depth.py", line 4, in <module>
    from mmdet.models.backbones.resnet import BasicBlock
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmdet/models/backbones/csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmdet/models/utils/__init__.py", line 16, in <module>
    from .transformer import (DetrTransformerDecoder, DetrTransformerDecoderLayer,
  File "/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmdet/models/utils/transformer.py", line 29, in <module>
    from mmcv.cnn.bricks.transformer import MultiScaleDeformableAttention
ImportError: cannot import name 'MultiScaleDeformableAttention' from 'mmcv.cnn.bricks.transformer' (/media/hjc/DeepLearning1/Anaconda3/envs/occdepth1/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py)

从 Windows 版邮件发送

发件人: Sihang Li
发送时间: 2023年4月3日 14:35
收件人: megvii-research/OccDepth
抄送: Jessy-Huang; Comment
主题: Re: [megvii-research/OccDepth] About Training processing (Issue #3)

mmcv与pytorch等库有对应版本，可以查看mmcv的官方文档进行选择
mmcv 1.4.0的可以运行，最新的cuda11.7对应的mmcv经测试也可以运行occdepth
或许你可以按照https://github.com/NVlabs/VoxFormer/blob/main/docs/install.md 试一试

**Comment by Jessy-Huang** [comment]
mmcv与pytorch等库有对应版本，可以查看mmcv的官方文档进行选择
mmcv 1.4.0的可以运行，最新的cuda11.7对应的mmcv经测试也可以运行occdepth
或许你可以按照https://github.com/NVlabs/VoxFormer/blob/main/docs/install.md 试一试

**Comment by Louis-Leee** [comment]
Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module.
我之前遇到过这个报错，事实上这仍然是mmcv-full没安装好的问题，将整个环境需要重新配置
请注意：python3.8 和 3.7有时候会影响结果
